DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  file_name TEXT UNIQUE NOT NULL,
  file_url TEXT NOT NULL,
  tags TEXT NOT NULL
);

